services:
  # This configuration is for a STATIC SITE (like a standard React app)
  - type: web
    name: my-portfolio1  # <-- CHANGE THIS to your Render service name
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    
    # --- THIS IS THE MAGIC PART THAT FIXES REFRESHES ---
    routes:
      - route: /(.*) 
        handler: spa
    # ----------------------------------------------------